version: '3.8'

services:
  db:
    container_name: ${APP_ID:-app}_db
    restart: unless-stopped
    build:
      context: ./services/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=${APP_ID:-app}_db
      - MYSQL_USER=${MYSQL_USER:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-admin}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ./services/mysql/data:/var/lib/mysql

  backend:
    container_name: ${APP_ID:-app}_backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./services/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
      - scraper
    environment:
      DB_CONNECTION: mysql
      DB_HOST: ${APP_ID:-app}_db
      DB_PORT: 3306
      DB_DATABASE: ${APP_ID:-app}_db
      SCRAPER_URL: http://${APP_ID:-app}_scraper:${SCRAPER_PORT:-4000}
      DB_USERNAME: ${MYSQL_USER:-admin}
      DB_PASSWORD: ${MYSQL_PASSWORD:-admin}

  scraper:
    container_name: ${APP_ID:-app}_scraper
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./services/scraper/Dockerfile
    volumes:
      - ./scraper:/app
    environment:
      SCRAPER_PORT: ${SCRAPER_PORT:-4000}
      TARGET_REVIEWS_COUNT: ${TARGET_REVIEWS_COUNT:-600}
      MAX_IDLE_SCROLLS: ${MAX_IDLE_SCROLLS:-5}
      FETCH_RESPONSE_TIMEOUT_MS: ${FETCH_RESPONSE_TIMEOUT_MS:-5000}
    ports:
      - ${SCRAPER_PORT:-4000}:${SCRAPER_PORT:-4000}

  frontend:
    container_name: ${APP_ID:-app}_frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./services/npm/Dockerfile
    ports:
      - ${VITE_PORT:-5173}:5173
    environment:
      VITE_API_URL: http://localhost:${NGINX_PORT:-80}/api
    volumes:
      - ./frontend:/app

  web:
    container_name: ${APP_ID:-app}_web
    restart: unless-stopped
    build:
      context: ./services/nginx
    ports:
      - ${NGINX_PORT:-80}:80
    environment:
      - APP_ID=${APP_ID:-app}
    volumes:
      - ./backend:/var/www/html
      - ./services/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend
      - frontend
